import Theme from '@/app/_utils/theme';
import { Paper } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './_components/header';
import { createClient } from '@/app/_utils/supabase/server';
import Background from './_components/background';
import { OpenProvider } from '@/app/_utils/context';
import { Suspense } from 'react';
import LoadingBackground from './(loading)/background';
// import { cookies } from 'next/headers';
// import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ToDoLoo',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	// const cookieStore = cookies();
	const supabase = createClient();

  const { data: { user } } = await supabase.auth.getUser();

	const { data: profile } = await supabase
	.from('profiles')
	.select('color')
	.eq('id', user?.id)
	.single();

	// if (!profile) return <p>Loading</p>;

  return (
    <html lang='en'>
			<Theme profileColor={profile?.color||null}>
				<Paper
					className={inter.className}
					component='body'
					elevation={0}
					square
					sx={{
						m: 0,
						height: '100vh',
					}}
				>
					<OpenProvider>
						<Header />
						{children}
						<Suspense fallback={<LoadingBackground />}>
							<Background />
						</Suspense>
					</OpenProvider>
				</Paper>
			</Theme>
    </html>
  );
}
